handy_helper/apps/jobs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<job_id>\d+)/update$', views.update, name="update"),
    url(r'^(?P<job_id>\d+)/add_job$', views.add_job, name="add_job"),
    url(r'^(?P<job_id>\d+)/cancel$', views.destroy, name="destroy"),
    url(r'^create$', views.create, name="create")

]

handy_helper/apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register$', views.create_user, name="create_user"),
    url(r'^login$', views.login, name="login"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^dashboard$', views.dashboard, name="dashboard"),
    url(r'^addjob$', views.addjob, name="addjob"),
    url(r'^(?P<id>\d+)/view$', views.view, name="view"),
    url(r'^(?P<job_id>\d+)/edit$', views.edit, name="edit")

]

handy_helper/handy_helper/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^jobs/', include('apps.jobs.urls', namespace="jobs")),
    url(r'^', include('apps.users.urls', namespace="users"))

]

handy_helper/apps/users/models.py
from django.db import models
import bcrypt
import re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def validate(self, form):
        errors = []
        if len(form['first_name']) < 2:
            errors.append('First name must be longer than 2 characters. Try again')
        if len(form['last_name']) <2:
            errors.append('Last name must be filled out. Try again.')
        if not EMAIL_REGEX.match(form['email']):
            errors.append('Please enter a valid email address.')
        if len(form['password']) <8:
            errors.append('Password should be at least 8 characters. Try again.')
        if form['password'] != form['confirm_pw']:
            errors.append('Passwords must match. Please try again.')
        print(errors)
        print(form)

        if self.filter(email=form['email']):
            errors.append('email address is already in use.')

        return errors

    def create_user(self, form_data):
        pw_hash = bcrypt.hashpw(form_data['password'].encode(), bcrypt.gensalt())
        user = self.create(
            first_name = form_data['first_name'],
            last_name = form_data['last_name'], 
            email = form_data['email'], 
            pw_hash=pw_hash,
        )
        
        return user

    def login(self, form):
        user_list = self.filter(email=form['email'])
        if len(user_list) > 0:
            user = user_list[0]
            if bcrypt.checkpw(form['password'].encode(), user.pw_hash.encode()):
                return (True, user.id, user.first_name)
            else:
                return(False, "Email or Password is not right.")

        else:
            return(False, "Email or Password is not right. Try again.")
        





# Create your models here.
class User(models.Model):
    first_name =  models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    pw_hash = models.CharField(max_length=500)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    objects = UserManager()

    def __str__(self):
        return "<User object: {} {}>" .format(self.first_name, self.last_name)

handy_helper/apps/users/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from .models import User
from ..jobs.models import Job
# Create your views here.
def index(request):
    return render(request, 'users/index.html')

def create_user(request):
    print(request.POST)
    if request.method != 'POST':
        return redirect('/')
    errors = User.objects.validate(request.POST)
    if len(errors) > 0:
        for error in errors:
            messages.error(request, error)
    user = User.objects.create_user(request.POST)
    request.session['user_id'] = user.id
    request.session['name'] = request.POST['first_name']
    return redirect('users:dashboard')

def login(request):
    if request.method != 'POST':
        return redirect('/')
    valid, response, name = User.objects.login(request.POST)
    if valid == True:
        request.session['user_id'] = response
        request.session['name'] = name
        return redirect('users:dashboard')
    else:
        messages.error(request,response)
    return redirect('/')
    
def logout(request):
    request.session.clear()
    return redirect('users:index')

def dashboard(request):
    context = {
        'user_info': User.objects.get(id=request.session['user_id']),
        'jobs' : Job.objects.all(),
        'my_jobs': Job.objects.filter(assignee_id=request.session['user_id'])
    }
    return render (request, 'users/dashboard.html', context)

def addjob(request):
    if 'user_id' not in request.session:
        return redirect('users:index')
    #this directs user to the add a job page.
    context = {
        'user_info': User.objects.get(id=request.session['user_id'])
    } 
    return render(request,'users/addajob.html', context)

def view(request, id):
    context = {
        'jobs' : Job.objects.get(id=id),
        'user_info': User.objects.get(id=request.session['user_id'])
    }
    return render(request, 'users/view.html', context)


def edit(request, job_id):
    context = {
        'edit_job' : Job.objects.get(id=job_id)
    }
    return render(request,'users/userquotes.html', context)

handy_helper/apps/users/templates/users/addajob.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        .header{
            margin-left: 944px;
            margin-top: 10px;
            margin-bottom: 10px;
        }
        .messages{
            color: red;
        }
    </style>
    <title>Add a Job</title>
  </head>
  <body>
    <div class="container">
        <div class="header">
            <a class="btn btn-primary" href="/dashboard">Back</a>
            <a class="btn btn-primary" href="/logout">Log Out</a>
        </div>
        <div class="form-group col-md-6">
        <h1>Add a Job {{ user_info.first_name }}</h1>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        <form action="{% url 'jobs:create'%}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="helper" value="{{ user_info.id }}">
            Title: <input class="form-control" type="text" name="title" id="">
            <br>
            Description: <textarea class="form-control" name="description" id="" cols="30" rows="10"></textarea> 
            <br>
            Location: <input class="form-control" type="text" name="location" id="">
            <br>
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

handy_helper/apps/users/templates/users/dashboard.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <style>
        .header{
            margin: 50px 0px 50px 0px;
        }

        h2 {
            display: inline-block;
            margin-right: 10px;
        }

        #joblink {
            margin-left: 700px;
        }

        .joblist {
            display: inline-block;
            border: black 2px solid;
        }

        .myjobs {
            display: inline-block;
            vertical-align: top;
            border: black 2px solid;
        }



    </style>
    <title>Handy Helper Dashboard</title>
</head>

<body>
    <div class="container">
    <div class="header">
    <h2>Hello {{ request.session.name }}</h2>
    <a class="btn btn-primary" href="/logout">Log Out</a>
    <a id="joblink" class="btn btn-primary" href="/addjob">Add a Job</a>
    </div>
    <div class="container">
            <div class="joblist">   
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Job</th>
                            <th scope="col">Location</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for job in jobs %}
                        <tr>
                            <td style="border-right: black 2px solid;"> {{ job.title }}</td>
                            <td style="border-right: black 2px solid;">{{job.location}}</td>
                            <td>
                                <a href="{% url 'users:view' job.id %}">View</a>
                                <a href="{% url 'users:view' job.id %}">Add</a> 
                                <a href="{% url 'users:edit' job.id %}">Edit</a>  
                                <a href="{% url 'jobs:destroy' job.id %}">Cancel</a>
 
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    
                </table>
            </div>
            <div class="myjobs">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">My Jobs</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for job in my_jobs %}
                            <tr>
                                <td style="border-right: black 2px solid;">{{job.title}}</td>
                                <td style="border-right: black 2px solid;"><a href="{% url 'users:view' job.id %}">View</a>  </td>
                                <td> <a href="{% url 'jobs:destroy' job.id %}">Done</a> </td>
                            </tr>
                            <tr>
                            {% endfor %}
                        </tbody>
                    
                    </table>
            </div>
            </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

handy_helper/apps/users/templates/users/index.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <style>
        .form-container{
            display: inline-block;
            vertical-align: top;
        }

        .messages{
            color: red;
        }
    </style>
    <title>A Web Page</title>
</head>

<body>
    <div class="container">
    <h1>Welcome to Handy Helper</h1>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    <div class="form-container">

        <form action="/register" method="POST">
        {% csrf_token %}
        <h2>Register</h2>
        First Name: <input type="text" name="first_name" id="">
        <br>
        Last Name: <input type="text" name="last_name" id="">
        <br>
        Email: <input type="text" name="email" id="">
        <br>
        Password: <input type="password" name="password" id="">
        <br>
        Confirm PW: <input type="password" name="confirm_pw" id="">
        <br>
        <input class="btn btn-primary" type="submit" value="Register">
        </form>
    </div>
    <div class="form-container">
        <h2>Login</h2>
        <form action="/login" method="POST">
        {% csrf_token %}
        Email: <input type="text" name="email" id="">
        <br>
        Password: <input type="password" name="password" id="">
        <br>
        <input class="btn btn-primary" type="submit" value="Log In">
        </form>
    </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

handy_helper/apps/users/templates/users/userquotes.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <style>
        .header{
            margin-left: 944px;
            margin-top: 10px;
            margin-bottom: 10px;
        }
    </style>
    <title>User Quotes</title>
</head>

<body>
    <div class="container">
        <div class="header">
            <a class="btn btn-primary" href="/dashboard">Back</a>
            <a class="btn btn-primary" href="/logout">Log Out</a>
        </div>
        <div class="form-group col-md-6">
            <h1>Edit Your Job Posting</h1>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            <form action="{% url 'jobs:update' edit_job.id %}" method="POST">
                {% csrf_token %}
                Title: <input type="text" name="title" placeholder = "{{ edit_job.title }}"> 
                <br>
                Description: <textarea name="description" placeholder = "" cols="30" rows="10">{{ edit_job.description }}</textarea>
                <br>

                Location: <input type="text" name="location" placeholder ="{{edit_job.location}}"> 
                <br>
                <input class="btn btn-primary" type="submit" value="Submit">
            </form>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

handy_helper/apps/users/templates/users/view.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <style>
        .header{
            margin-left: 944px;
            margin-top: 10px;
            margin-bottom: 10px;
        }

        .form {
            border: black 2px solid;
            padding:  10px;
        }
    </style>
    <title>View Job</title>
</head>

<body>
    <div class="container">
        <div class="header">
            <a class="btn btn-primary" href="/dashboard">Back</a>
            <a class="btn btn-primary" href="/logout">Log Out</a>
        </div>
        <div class="form-group col-md-6">
            <h1>{{jobs.title}}</h1>
            <form class="form" action="{% url 'jobs:add_job' jobs.id %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="title" value="{{jobs.title}}">
                <input type="hidden" name="description" value="{{jobs.description}}">
                <input type="hidden" name="location" value="{{jobs.location}}">
                <input type="hidden" name="helper" value="{{ user_info.id }}">
                {{jobs.description}}
                <br>
                {{jobs.location}}
                <br>
                Posted by: {{jobs.assignee_id.first_name}}
                <br>
                Posted on: {{jobs.created_at}}
                <br>
                <input class="btn btn-primary" type="submit" value="Add to My Jobs">
            </form>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>